baseURL = "http://hank-krutulis.com/"
languageCode = "en-us"
title = "Hank Krutulis"
theme = "hugo-developer-portfolio"


# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  # [[menu.main]]
  # name = "About"
  # URL = "#about"
  # weight=1

  [[menu.main]]
  name = "Skills"
  URL = "#skills"
  weight=2

 [[menu.main]]
  name = "Experience"
  URL = "#experience"
  weight=3

  [[menu.main]]
  name = "Portfolio"
  URL = "#portfolio"
  weight=4

  [[menu.main]]
  name = "Extracurriculars"
  URL = "#extracurriculars"
  weight=5

[params]
home = "Home"
# Meta data
description = "Hank's fancy, dancy site!"
author = "Hank Krutulis"


[params.contact]
  enable = true
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "henrykrutulis@gmail.com"
  address = "West Lafayette, IN, US"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4
